### **Juami Shaniqua Desio BSIS-3A**
#**IS 110**

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [19]:
%cd /content/drive/MyDrive/IS110_BPerformance_Desio/IS110_repo_Desio

/content/drive/MyDrive/IS110_BPerformance_Desio/IS110_repo_Desio


In [20]:
!pwd

/content/drive/MyDrive/IS110_BPerformance_Desio/IS110_repo_Desio


#**EXERCISE A**

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [ ]:
import numpy as np

In [ ]:
A = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
print("Shape of A:", A.shape)

Shape of A: (2, 3)


In [ ]:
print("Max value using method:", A.max())

Max value using method: 60


In [ ]:
print("Max value using np function:", np.max(A))

Max value using np function: 60


#**EXERCISE B**

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [ ]:
B = np.ones((5, 5), dtype=int)

In [ ]:
print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
print("Shape:", B.shape)

Shape: (5, 5)


In [ ]:
print("Size:", B.size)

Size: 25


In [ ]:
print("Dimensions:", B.ndim)

Dimensions: 2


#**EXERCISE C**

In [ ]:
C = np.arange(-5, 6)

In [ ]:
result = C * 2

In [ ]:
print("Original Array:", C)

Original Array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [ ]:
print("Resulting Array:", result)

Resulting Array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


#**PUSH in PythonEnvi_Desio and GIT**

In [24]:
!find /content/drive/MyDrive -name "Chapter5_NumPyExercise.ipynb"

/content/drive/MyDrive/IS110_BPerformance_Desio/IS110_repo_Desio/PythonEnvi_Desio/Chapter5_NumPyExercise.ipynb
/content/drive/MyDrive/IS110_BPerformance_Desio/Chapter5_NumPyExercise.ipynb


In [25]:
!git config --global user.email "juamishaniqua.desio@students.isatu.edu.ph"
!git config --global user.name "Juami Shaniqua Desio"

In [26]:
!cp "/content/drive/MyDrive/IS110_BPerformance_Desio/Chapter5_NumPyExercise.ipynb" "/content/drive/MyDrive/IS110_BPerformance_Desio/IS110_repo_Desio/PythonEnvi_Desio/"

In [27]:
!ls

Chapter2.ipynb	IS110_repo_Desio  newupload.txt  PythonEnvi_Desio  world.py


In [30]:
!git add "PythonEnvi_Desio/Chapter5_NumPyExercise.ipynb"

In [32]:
!git status

Refresh index: 100% (5131/5131), done.
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   PythonEnvi_Desio/Chapter5_NumPyExercise.ipynb

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   PythonEnvi_Desio/myenv/bin/python
	modified:   PythonEnvi_Desio/myenv/bin/python3
	modified:   PythonEnvi_Desio/myenv/bin/python3.12

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	IS110_repo_Desio/



In [33]:
!git commit -m "Add Chapter5 NumPy Exercise"

[main f021bed] Add Chapter5 NumPy Exercise
 1 file changed, 1 insertion(+)
 create mode 100644 PythonEnvi_Desio/Chapter5_NumPyExercise.ipynb


In [34]:
!git push -u origin main

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 2.66 KiB | 545.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/wamichuchuu/IS110_repo_Desio.git
   d4111dc..f021bed  main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
